### PR TITLE
Build 0.5.0

### PR DESCRIPTION
**Pull request by megies**

### CODE REVIEW

**Comment by megies** [comment]
OSX passing. Travis is taking forever. Assuming it should work as well, so merging to avoid waiting for Travis and then again waiting for the real build..

**Comment by megies** [comment]
@conda-forge/core  can somebody please restart this CircleCI build? Somehow I don't have the rights to do so..  ("You need write permissions to trigger builds")

screenshot from 2017-11-08 08-38-10



https://circleci.com/gh/conda-forge/obspyck-feedstock/27?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

It was passing in here and it looks like a pure network fail to me:

screenshot from 2017-11-08 08-40-08

**Comment by megies** [comment]
Nevermind, I pushed a dummy commit to master to get a new build.

**Comment by jakirkham** [comment]
There may be some GitHub and/or CircleCI settings tweaking needed @megies.

**Comment by megies** [comment]
> There may be some GitHub and/or CircleCI settings tweaking needed @megies.

Nah, that was really just a fluke network fail.

**Comment by jakirkham** [comment]
Was referring to the inability to restart.

**Comment by megies** [comment]
Ah, OK..

**Pull request merged**
